name: Build ImmortalWrt For R4S (Stable 25.12 + MosDNS APK)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo docker image prune -a -f

      - name: Download Image Builder
        run: |
          export STABLE_VERSION="25.12.0"
          curl -s https://downloads.immortalwrt.org/releases/$STABLE_VERSION/targets/rockchip/armv8/ -o page.html
          FILE_NAME=$(grep -o 'immortalwrt-imagebuilder-[^"]*-rockchip-armv8\.Linux-x86_64\.tar\.[a-z]*' page.html | head -n 1)
          wget "https://downloads.immortalwrt.org/releases/$STABLE_VERSION/targets/rockchip/armv8/$FILE_NAME"
          tar -a -xf $FILE_NAME
          mv immortalwrt-imagebuilder-*/ ib/

      - name: Inject MosDNS Packages (APK Native)
        run: |
          cd ib/
          mkdir -p packages
          
          # 直接下载你查到的 sbwml 大佬专为 25.12 (apk架构) 准备的压缩包
          wget https://github.com/sbwml/luci-app-mosdns/releases/download/v5.3.4-r5/aarch64_generic-openwrt-25.12.tar.gz
          
          # 直接解压到 packages 目录中，里面包含了所有需要的 apk 和索引
          tar -zxf aarch64_generic-openwrt-25.12.tar.gz -C packages/
          
          # 刷新包管理器索引
          make package_index

      - name: Configure and Build
        run: |
          cd ib/
          
          mkdir -p files/etc/uci-defaults/
          
          cat << 'EOF' > files/etc/uci-defaults/99-custom-settings
          uci set network.lan.ipaddr='192.168.100.1'
          uci commit network
          uci set system.@system[0].timezone='CST-8'
          uci set system.@system[0].zonename='Asia/Shanghai'
          uci commit system
          /etc/init.d/dockerd disable
          EOF
          chmod +x files/etc/uci-defaults/99-custom-settings

          # MosDNS 完美回归，直接打包
          make image PROFILE="friendlyarm_nanopi-r4s" \
            PACKAGES="luci-app-zerotier luci-proto-wireguard luci-app-openclash luci-app-homeproxy luci-app-dae luci-app-vlmcsd luci-theme-argon luci-app-argon-config luci-app-upnp luci-app-ddns-go luci-app-mosdns luci-app-adguardhome luci-app-dockerman docker dockerd luci-app-samba4 block-mount kmod-usb-storage kmod-fs-ext4 e2fsprogs fdisk cfdisk parted resize2fs lsblk luci-app-hd-idle luci-app-ttyd luci-app-wol luci-app-irqbalance irqbalance iperf3 luci-app-nlbwmon bash curl wget-ssl htop" \
            FILES="files"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt_R4S_Firmware_25.12.0_MosDNS
          path: ib/bin/targets/rockchip/armv8/*sysupgrade.img.gz
